### ISSUE TITLE
how to restore a backup

### ISSUE THREAD

**Issue by andreascschmidt** [fr0tt/benotes#104]
Silly question, but how do I restore a backup .zip to a new installation when using the docker-compose version? 

Is there maybe even a way to restore a postgresql backup to a new install using SQLite? 

Thanks

**Comment by fr0tt** [comment]
Apologies for the late response!

If you want to restore it you have to unzip the backup and put the `storage` folder inside your installation by replacing the existing `storage` folder.
This only works if you manage to restore/import your database data as well.


Importing data from PostgreSQL to Sqlite could be achieved by installing a tool like https://github.com/caiiiycuk/postgresql-to-sqlite and putting the sqlite database inside the famous `storage` folder as `database.sqlite` and changing in your `.env` file the variable `DB_CONNECTION` to `DB_CONNECTION=sqlite`
