### ISSUE TITLE
Database connection [postgres] not configured.

### ISSUE THREAD

**Issue by 0x01x0** [fr0tt/benotes#14]
Database connection [postgres] not configured.

**Comment by fr0tt** [comment]
You have two options to configure a postgresql connection.

The first one would be to use something like that in your `.env` file:

```
DB_CONNECTION=pgsql
DB_HOST=localhostOrYourDatabaseIpAddress
DB_PORT=5432
DB_DATABASE=YourDatabaseName
DB_USERNAME=YourDatabaseUsername
DB_PASSWORD=YourDatabasePassword
```

The other one would be to use as an alternative a connection string:

`DB_URL=postgres://username:password@localhost:5432/yourdatabasename`


I also improved the installation section and added default values for a postgresql database connection.

**Comment by 0x01x0** [comment]
where is DB_URL？

**Comment by fr0tt** [comment]
Sorry my anwser was a little misleading. I edited and improved it.

I hope this anwsers your question. If not add more context about your situation for me so I can better understand your problem.

**Comment by 0x01x0** [comment]
NO NO NO ! I'm rookie!!!!

**Comment by fr0tt** [comment]
Please close the issue if your problem has been solved. If not, don't hestitate to ask.
