### ISSUE TITLE
Docker image stuck in "restarting" upon system reboot

### ISSUE THREAD

**Issue by korikori** [fr0tt/benotes#19]
Hi there, I've installed your app via its docker image, but whenever I have to reboot the server hosting it, Benotes fails to start up - it just keeps on restarting itself unsuccessfully. The only relevant line in the logs is this:

error: failed switching to "root": operation not permitted

Restarting the app with docker-compose down and docker-compose up works, but restarting the docker service or rebooting the machine results in the same failure.

I worked around this by adding the following line to the docker-compose.yml file within the service block for "app":

user: root

However, I am way too unfamiliar with docker to know if this is a cause for concern or not.

**Comment by fr0tt** [comment]
Hey, thank you for reporting this issue !

I will look into it once I'm back at home in a couple of days. 

A quick search resulted in a lot of different causes for this error, it's seems quit common. But I have to try to recreate your bug and see how things go from there.

**Comment by fr0tt** [comment]
As far as I understand this is not a cause for concern.
So based on this [issue](https://github.com/webdevops/Dockerfile/issues/366) on the base image I hopefully fixed your bug. 

Let me know if it's still a problem or you find another one.
If not please close this issue.

**Comment by korikori** [comment]
Thanks for looking into this, and sorry for taking so long to get back to you/close. All the best.

**Comment by fr0tt** [comment]
With pleasure and no worries, I was just a little concerned something was wrong, but I'm glad that wasn't the case ;) All the best for you too.
