### ISSUE TITLE
Error when restore post

### ISSUE THREAD

**Issue by dimon1985** [fr0tt/benotes#29]
When click on restore icon:
`app.js:2 TypeError: t.restoreFunc is not a function
    at click (app.js:2:582087)
    at Kt (app.js:2:27360)
    at HTMLButtonElement.n (app.js:2:29151)
    at HTMLButtonElement.i._wrapper (app.js:2:64834)`
<img width="1373" alt="Screenshot 2022-04-02 at 14 41 54" src="https://user-images.githubusercontent.com/8317488/161381470-15f42420-a7c2-44be-a55f-42e20d6af3e8.png">

**Comment by fr0tt** [comment]
Hi, thanks for pointing out this obvious mistake !
(I didn't encounter it thanks to some nasty browser caching.)
It should be fixed now.

If it is indeed solved for you as well, please close the issue.
