### ISSUE TITLE
Add image to Docker Hub

### ISSUE THREAD

**Issue by AuthorShin** [fr0tt/benotes#30]
Hello
when will you consider adding the docker image to hub.docker.com?

**Comment by AuthorShin** [comment]
Thank you very much, and I would highly appreciate it if possible it will be just one container not a stack so it will be much more easier to install and deploy on docker management systems like casaOS.

**Comment by fr0tt** [comment]
So it took me a while but after some research into CasaOS ( I saw your docker-compose issue :) ), how it works and apps that already work with it I think I finally made it happen.
Originally I wanted to separate the database but after your comment I decided to support SQLite which allows me to put everything in one image.

You can find the docker image [here](https://hub.docker.com/r/fr0tt/benotes)
and installation instructions [here](https://github.com/fr0tt/benotes/blob/master/installation.md#docker-with-cli).

It is safe to say that things are a little bit more complicated with CasaOS because as far as I researched env-file and named volumes are not supported.
Meaning you have to set all variables from this [file](https://raw.githubusercontent.com/fr0tt/benotes/master/.env.sqlite.example) as environment variables. (Perhaps it's already enough if you only set `APP_KEY`, `JWT_SECRET`, `DB_CONNECTION`, `APP_ENV` and `APP_URL`)

Also regarding the volumes you need to define 4 volumes (except if you have found a way to use named volumes that is).
Let's say you have created a folder called benotes in CasaOS:
- benotes/nginx/logs/:/var/lib/nginx/logs/
- benotes/storage/database.sqlite:/var/www/storage/database.sqlite 
- benotes/storage/app/public/thumbnails:/var/www/storage/app/public/thumbnails 
- benotes/storage/logs:/var/www/storage/logs 

If you have any questions or should it not work (as expected) do not hesitate to ask me.

**Comment by AuthorShin** [comment]
@fr0tt Thanks a lot man
I tried to setup it as you said and container start running but it's not showing anything on the webpage and I got this in the logs:
`B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable
B-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
<-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
>-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
:-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
--> Executing /entrypoint.d/app_entrypoint.sh
J/entrypoint.d/app_entrypoint.sh: line 7: RUN_MIGRATIONS: unbound variable`

**Comment by fr0tt** [comment]
Your welcome !

Oh that was a rather obvious mistake of mine. You need to add `RUN_MIGRATIONS` (set to `false`).

**Comment by AuthorShin** [comment]
@fr0tt Thanks for the help, it's up and running but stuck in login page.
<img src="https://i.ibb.co/SQCGqFN/Screenshot-2022-06-08-205126.png" alt="Benotes stuck at login page">

**Comment by fr0tt** [comment]
Have you already executed those two commands (mentioned in the [documentation](https://github.com/fr0tt/benotes/blob/master/installation.md#docker-with-cli)) ? (You can execute them in Casa in the container's settings by clicking on the terminal icon in the upper right corner.)
```
php artisan migrate
php artisan install --only-user
```

**Comment by AuthorShin** [comment]
@fr0tt Unfortunately, my casaOS is kinda corrupted so that terminal for each container is not working.

**Comment by AuthorShin** [comment]
Using SSH I got these errors:
<img src="https://i.ibb.co/JjgJTkz/Screenshot-2022-06-08-224642.png" alt="Error when executing command inside the benotes docker container">

**Comment by fr0tt** [comment]
Strange, it definitely has something to do with your database but I'm not quite sure what it is.

Can you tell me what environment variables you set for the database ?
There are two working possibilities and it should be either:
```
DB_CONNECTION=sqlite
```
or
```
DB_CONNECTION=sqlite
DB_HOST=
DB_PORT=
DB_DATABASE=storage/database.sqlite
DB_USERNAME=
DB_PASSWORD=
``` 

If that's not the issue then can you tell me what permission does the file /var/www/storage/database.sqlite has ? (with e.g. the command `ls -l`) It should be `-rw-r--r--  applicat(ion):applicat`

**Comment by AuthorShin** [comment]
@fr0tt I removed the directory from the previous attempts and then create folder and database file and then install the container as you said and then run those two commands and boom, it's working =D
Thanks a lot man, thanks a lot

**Comment by AuthorShin** [comment]
A little suggestion to add latest tag in hub.docker.com so if you update the container we can easily update it even via something like watchtower.

**Comment by fr0tt** [comment]
I'm glad it works, thanks for being so patient. And your welcome. I know it can be quite frustrating sometimes to install something ;)

I already realized that and added that tag yesterday (, it's the most important one after all).

**Comment by AuthorShin** [comment]
@fr0tt Thank you for all the time and effort :)
