### ISSUE TITLE
Not able to create new post/collection

### ISSUE THREAD

**Issue by AuthorShin** [fr0tt/benotes#34]
Hello
When I try to create a new collection nothing happens and when trying to crease new post I got the following error on the down right of the screen.

Error

Post could not be created. 

Also trying to edit the default posts I got this error:

Error

Post could not be updated.

**Comment by fr0tt** [comment]
Not sure what is causing that.
There should be a file called `storage/logs/lumen-2022-06-11.log`. Can you tell me its content ?

**Comment by AuthorShin** [comment]
Here you go man:


[lumen-2022-06-09.log](https://github.com/fr0tt/benotes/files/8884404/lumen-2022-06-09.log)
[lumen-2022-06-11.log](https://github.com/fr0tt/benotes/files/8884405/lumen-2022-06-11.log)

**Comment by fr0tt** [comment]
Thanks, so the issue seems that your database is not writable which means it's a permission issue.

Try to fix it where you placed your volumes with `sudo chown 1000:1000 database.sqlite && sudo chmod 774 database.sqlite`.

**Comment by AuthorShin** [comment]
@fr0tt 
Thanks man it worked :)
Quick bug report:
When creating a new collection if you select a new icon and save it, it will be still the default one and you have to edit it and re select the icon and save it in order to show up.

**Comment by AuthorShin** [comment]
NP man, I will try to record a video for this one when got spare time.

**Comment by fr0tt** [comment]
The newest version should have fixed your problems. 
Let me know if you can confirm that and please explain your 3rd issue to me again - if it's still an issue.
