### ISSUE TITLE
CORS error, Loading css externally.

### ISSUE THREAD

**Issue by MohamedElashri** [fr0tt/benotes#45]
In firefox, Many people (like me) enable `security.fileuri.strict_origin_policy` because of the security (and privacy) implications. However this makes the app inaccissable because it tries to load css file from `https://rsms.me/inter/inter.css` inside `app.blade.php` file . I think it is good idea to add this file locally and load it from there.

**Comment by fr0tt** [comment]
Ok, am going to change that

**Comment by MohamedElashri** [comment]
any update?

**Comment by fr0tt** [comment]
I already pushed it to the dev branch a while back so you can try it out if you want or you have to wait a little while longer until I merge it with the master branch (when the rest of my changes are stable enough).

**Comment by fr0tt** [comment]
Is now part of the master branch.

**Comment by MohamedElashri** [comment]
Thanks, works great!
