### ISSUE TITLE
Docker setup is too cumbersome

### ISSUE THREAD

**Issue by ItsNoted** [fr0tt/benotes#48]
Is there any way to simplify the Docker Compose setup? I've been pulling hair out trying to get this working so I can review it 😆😂

Using Docker CLI I get this error after following the instructions to a T.

`[2023-01-13 17:14:14] production.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/vendor/illuminate/view/Compilers/Compiler.php:36)
`

**Comment by fr0tt** [comment]
I'm going to work on adding a second docker-compose option.


Regarding your error: it seems some/all of your storage/... subfolders are missing. It is most likely a permission issue.

**Comment by fr0tt** [comment]
I have simplified it. If is to your liking and it works please close the issue.

**Comment by ItsNoted** [comment]
> I have simplified it. If is to your liking and it works please close the issue.

Hi there.

Can you please explain what you did or link to the update? I don't see it. Clearly I am overlooking it.

Thank you!

**Comment by fr0tt** [comment]
I'm sorry, I thought you knew what I was talking about. I meant the [documentation](https://benotes.org/docs/installation/docker-compose)

**Comment by ItsNoted** [comment]
Got it up and running. Thanks!

**Comment by fr0tt** [comment]
No problem !
