### ISSUE TITLE
[Feature Request] Dark mode!

### ISSUE THREAD

**Issue by ItsNoted** [fr0tt/benotes#49]
Ok, so after getting this setup finally, I realized this will be something I use ALOT. That being said, a dark mode would be fantastic so it is easier on the eyes.

**Comment by fr0tt** [comment]
I'm happy to here that ! 
@godsgood33 asked already for theming in the past. I have to investigate what might be easier to implement (first), theming (with a dark theme) or a darkmode

**Comment by ItsNoted** [comment]
> I'm happy to here that ! @godsgood33 asked already for theming in the past. I have to investigate what might be easier to implement (first), theming (with a dark theme) or a darkmode

Ah ok thank you!

**Comment by fr0tt** [comment]
What did you have an mind when it comes to saving your preferred mode/theme, per browser/device or user account wide ?

**Comment by fr0tt** [comment]
Implemented.
