### ISSUE TITLE
[Feature Request] Code Block support

### ISSUE THREAD

**Issue by ItsNoted** [fr0tt/benotes#50]
I see there is support for inline code. But I like to save code snippets. Code block with a "copy" function would be great!

**Comment by ItsNoted** [comment]
Code Block is supported but it just doesn't format the code with a box around it which we are used to seeing. Create the note, paste your code then wrap the block code around it. Save it then click the note to copy the code to clipboard. 

I figured this out on my own ;)

**Comment by fr0tt** [comment]
It will still be a good idea to improve visibility/styling and even perhaps add syntax highlighting
