### ISSUE TITLE
Error: Post could not be updated

### ISSUE THREAD

**Issue by ItsNoted** [fr0tt/benotes#51]
I am getting these messages when creating, editing and moving notes. However it still does the task.

![image](https://user-images.githubusercontent.com/57927413/212564523-104866e8-6ebf-494f-8034-cd6c49ca20c8.png)

I wast too concerned because it's doing the tasks and the logs show one error here...

![image2](https://snip.lol/KeRi8/KARocUqI21.png/raw)

Any ideas what could be the issue? Should the PID and UID be stated in the compose file? Or is it a permission issue?

**Comment by ItsNoted** [comment]
After digging deeper I decided to check some things and it turned out to be the thumbnails directory needed write permissions.

```chmod -R 774 PWD$/data/storage/app/public/thumbnails```

**Comment by fr0tt** [comment]
Indeed the storage directory needs to be writable by the webserver. However I'm not sure what causes the directory to have other permission in the first place, because in the entrypoint script (since v2.4.0) for docker permissions are set for the storage directory.
