### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by galgofa** [fr0tt/benotes#53]
![IMG_20230116_224702](https://user-images.githubusercontent.com/94452175/212763403-a13e5356-c148-48aa-8dff-bbdba7df9ac6.jpg)
Thank you for the app. Trying to test but after php artisan install have a permission error, can you please have a look?

**Comment by fr0tt** [comment]
Thank you for saying that ;)
Sure thing. What method did you use to install it ? And probably nonetheless do you have an .env file ?

**Comment by galgofa** [comment]
Thanks for respond, initially i started with instructions from https://noted.lol/benotes/ but then github here, same issue.
.env file i have used with amendment for different port 8099 only, the rest as per default. 
I can run "php artisan install --only-user" and insert user/email/pass, web page is available but can't login

**Comment by fr0tt** [comment]
What I exactly meant was if you use docker (compose) or if you try to install it on the host system old-school without docker, but I presume you use docker-compose?

I asked if you have an .env file because I thought you maybe forgot to copy .env.example as .env but it that's not the case try to make the .env file writable for your current user.

**Comment by galgofa** [comment]
> try to make the .env file writable for your current user.
That's it !
Thank you vm, problem solved.

**Comment by fr0tt** [comment]
No problem !

**Comment by MohamedElashri** [comment]
Is `chmod 664 .env` what solved this problem or what (running this on the host)? I'm still having the same problem. 
Also, it is better if this is added as a step in docker-compose documentation

**Comment by fr0tt** [comment]
The reason why it isn't included is that it should not happen. Usually the directory you put everything in should be owned by your current user and then you won't face that problem.

**Comment by fr0tt** [comment]
The reason why it isn't included is that it should not happen. Usually the directory you put everything in should be owned by your current user and then you won't face that problem.

**Comment by MohamedElashri** [comment]
> 

This happens even with root access

**Comment by MohamedElashri** [comment]
> The reason why it isn't included is that it should not happen. Usually the directory you put everything in should be owned by your current user and then you won't face that problem and won't have to use chmod 774 or 744

After some thinking, yes you right about that. Anyway `docker-compose exec app sh` will solve this problem and  `.env` to 664.
