### ISSUE TITLE
[Feature Request] Bookmarks im/export

### ISSUE THREAD

**Issue by rauschgiftengel** [fr0tt/benotes#58]
First things first: great app, looks promising. 

But i am missing the function to import bookmarks. Is there a plan for that ?

**Comment by fr0tt** [comment]
Thank you !

There is currently no import function (unless doing it yourself via the rest api counts). 
To be honest it is a little bit of a delicate topic because everyone has a different understanding how the data is originally structured/which format is being used. 
What format would you have in mind to import from ?

**Comment by e-p-s** [comment]
bookmarks.html from any chromium and firefox?

**Comment by e-p-s** [comment]
perhaps is a useful way to write folders into tags?

**Comment by fr0tt** [comment]
Perhaps.

True, this makes it even more complicated ;)

**Comment by fr0tt** [comment]
An alternative for nested folders would be to flatten the structure.

But then I thought about it again and decided to simply just implement nested folders/collections, which would be a win-win situation.

**Comment by royalgarter** [comment]
Personally, I think the Import ( and Export maybe) is the very important feature for the common sense of users. Most of the users that know Benotes should already use some form of Bookmarks app. So we could allow the duplicated issue for the short terms, and bring it on asap with  the simple conversion from folders to tags.

**Comment by fr0tt** [comment]
It is now possible in the newest version [2.8.0](https://hub.docker.com/layers/fr0tt/benotes/2.8.0-beta/images/sha256-be2108e69cda44c993d1388ce5e6b9117b9076ce5ffb89a418451157d45b75c7) which is still in beta, just to be safe. Every browser might behave a little differently.
