### ISSUE TITLE
Correct s3 backup instructions

### ISSUE THREAD

**Issue by MohamedElashri** [fr0tt/benotes#59]
In `README` the part about s3 backup part in `.env` file will not work and `php artisan install` will complain about spaces. 

I think the correct way is to write
 
```
BACKUP_DISK= s3
AWS_ACCESS_KEY_ID= yourKeyId
AWS_SECRET_ACCESS_KEY = yourAccessKey
AWS_DEFAULT_REGION= us-east-1
AWS_BUCKET= yourCreativeBucketName
AWS_ENDPOINT= endpointUrl
```

Also 

```
BACKUP_INTERVAL=0 0 */7 * *
```
will give 

```
Failed to parse dotenv file. Encountered unexpected whitespace at [0 0 */7 * *].
```

I tried different syntaxes and still the same problem. I'm not an expert in PHP but I don't think we can have cron syntax with whitespace. Or maybe I'm missing something here.

**Comment by fr0tt** [comment]
Thanks ! 
You're right, I have to change that. 

(Btw I'm pretty sure `BACKUP_INTERVAL="0 0 */7 * *"` is going to work.)

**Comment by fr0tt** [comment]
Should be corrected
