### ISSUE TITLE
Error while php artisan install

### ISSUE THREAD

**Issue by Neules** [fr0tt/benotes#70]
I followed every step from [docs](https://benotes.org/docs/installation/docker-compose), but when I enter docker shell to `php artisan install` this happens:

```bash
php artisan install
Initiate installation...


0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? (yes/no) [no]:
> yes

Application key set successfully.
1/4 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  25%
This will invalidate all existing tokens. Are you sure you want to override the secret key? (yes/no) [no]:
> yes

jwt-auth secret [SWfxPsPF0zaUoGb5KyPb5j5r2s3pEUHZDtLYLNIOkQrT3ZS3WrzCOEaX8I7dDHgq] set successfully.


2/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%

**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? (yes/no) [no]:
> yes


UnexpectedValueException

The stream or file "/var/www/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: No such file or directory
The exception occurred while attempting to log: The stream or file "/var/www/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: No such file or directory
The exception occurred while attempting to log: SQLSTATE[HY000] [1045] Access denied for user 'benotes'@'192.168.16.3' (using password: YES) (SQL: select * from information_schema.tables where table_schema = benotes and table_name = migrat
ions and table_type = 'BASE TABLE')
Context: {"exception":{"errorInfo":["HY000",1045,"Access denied for user 'benotes'@'192.168.16.3' (using password: YES)"]}}
Context: {"exception":{}}

at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
142▕             restore_error_handler();
143▕             if (!is_resource($stream)) {
144▕                 $this->stream = null;
145▕
➜ 146▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url) . Utils::getRecordMessageForException($record));
147▕             }
148▕             stream_set_chunk_size($stream, $this->streamChunkSize);
149▕             $this->stream = $stream;
150▕         }

+9 vendor frames
10  [internal]:0
Illuminate\Foundation\Bootstrap\HandleExceptions::handleException(Object(UnexpectedValueException))
```

I'm pretty new with docker so I'm using portainer with a lot of other apps. I comment this because I thought it was a port error from mysql (I've had to change other mysql ports in the past to get things working), but I neither editing `docker-compose.yml` and manually hardcoding the port or editing `DB_PORT` at `.env` works.

While the `php artisan install` I choose yes on every step, but in the third I get this error.

Every file in the directory created by the git clone is writable by user and my user is the owner.

Thanks

**Comment by fr0tt** [comment]
Can you check if the path /var/www/storage/logs/laravel.log actually exists (or at least the directory /var/www/storage/logs) ?

Otherwise you need to make sure that you execute this command with the same user who owns /var/www/storage

**Comment by Neules** [comment]
`/var/www/storage/logs` exists, but it's empty. The owner is application:www-data`:

```bash
drwxr-xr-x    0 applicat www-data         0 Apr 17 16:30 logs
```

**Comment by fr0tt** [comment]
That's strange. 
Just to be sure you use `docker-compose exec --user application app sh` ? 
What are the permissions on the volume from the outside (docker/data/...) ?
And do you have an user on your system with id 1000 ?

**Comment by Neules** [comment]
> That's strange. Just to be sure you use `docker-compose exec --user application app sh` ? 
Yup.

> What are the permissions on the volume from the outside (docker/data/...) ? 
Mmm I don't really know what you are asking... I went to personal folder, then git clone the project and into the folder created by git do what's in the [docs](https://benotes.org/docs/installation/docker-compose), but if you mean if I created a volume or something the answer is no. Otherwise, tell me which location I should look for, please.

> And out of curiosity do you have an user on your system with id 1000 ?
Yup.
![uid](https://user-images.githubusercontent.com/34288954/232692196-b773e71f-63a9-4dd0-a709-5dfd9c6737c4.png)

**Comment by fr0tt** [comment]
I'm talking about the directory that should be created inside the directory with your docker-compose.yml file (after you start the container containing the bind mounts). However in my previous post I wrote `docker/data/` it's actually just `data/`, sorry. 
It should be owned by your user so use something like `sudo chown -R 1000 data`. Maybe that's the issue.

**Comment by Neules** [comment]
I've owned this folder recursively (`chown -R`), then I enter docker's shell (`docker-compose exec --user application app sh`) and `php artisan install` throw me this:

```bash
docker-compose exec --user application app sh
/var/www $ php artisan install
Initiate installation...


0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? (yes/no) [no]:
> yes

Application key set successfully.
1/4 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  25%
This will invalidate all existing tokens. Are you sure you want to override the secret key? (yes/no) [no]:
> yes

jwt-auth secret [BEHpMemKYHFFYRS16jXkjFjOccbXGkyQBVfkRTjGIZSvX5tgZRwd2Xza68q3tZhy] set successfully.


2/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%

**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? (yes/no) [no]:
> yes


Illuminate\Database\QueryException

SQLSTATE[HY000] [1045] Access denied for user 'benotes'@'192.168.16.3' (using password: YES) (SQL: select * from information_schema.tables where table_schema = benotes and table_name = migrations and table_type = 'BASE TABLE')

at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
708▕         // If an exception occurs when attempting to run a query, we'll format the error
709▕         // message to include the bindings with SQL, which will make this exception a
710▕         // lot more helpful to the developer instead of just the database's errors.
711▕         catch (Exception $e) {
➜ 712▕             throw new QueryException(
713▕                 $query, $this->prepareBindings($bindings), $e
714▕             );
715▕         }
716▕     }

+30 vendor frames
31  app/Console/Commands/InstallCommand.php:57
Illuminate\Console\Command::call("migrate")

+13 vendor frames
45  artisan:37
Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by fr0tt** [comment]
We're making some progress.
`Access denied` means that your database user `benotes` misses permissions (or that it can't access the database at all but I'm not sure about that).

**Comment by Neules** [comment]
So I'm bit lost here. I've defaults conf in `.env` (except for http port):

```bash
APP_PORT=8002

RUN_MIGRATIONS=false

APP_NAME=Benotes
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost:${APP_PORT}
APP_TIMEZONE=UTC

APP_KEY=base64:EAB3rEAqCq8O7FOx/JPQ/93q8P9EXcSOdb0bpi1M6wk=
JWT_SECRET=AxKmmeQLD1fi6Wi8C6apNDDYlFKlyaANKp72FRiV1wFOnPiXDSu9yhx8Rk3I5MIF
USE_FILESYSTEM=true

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3386
DB_DATABASE=benotes
DB_USERNAME=benotes
DB_PASSWORD=benotes

CACHE_DRIVER=file
QUEUE_CONNECTION=sync

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME="Benotes"

JWT_ALGO=HS256
```

Everything else is untouched.

**Comment by PDXUser** [comment]
Mine is a bit different, following the same guide.  When running the php artisan install - I get:
```
root@nas:~/compose/benotes# docker-compose exec --user application app sh
/var/www $ php artisan install
Initiate installation...


 0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%


   ErrorException 

  file_put_contents(/var/www/.env): Failed to open stream: Permission denied

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php:96
     92▕     {
     93▕         file_put_contents($this->laravel->environmentFilePath(), preg_replace(
     94▕             $this->keyReplacementPattern(),
     95▕             'APP_KEY='.$key,
  ➜  96▕             file_get_contents($this->laravel->environmentFilePath())
     97▕         ));
     98▕     }
     99▕ 
    100▕     /**

      +13 vendor frames 
  14  app/Console/Commands/InstallCommand.php:47
      Illuminate\Console\Command::call("key:generate")

      +13 vendor frames 
  28  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
/var/www $ 
```
Only item touched in the .env is the port to 3000 instead of 8000.

**Comment by fr0tt** [comment]
I tried to replicate it with your configuration and it failed. (I actually forgot to investigate if it's because you changed DB_PORT).
What worked for me was to download a fresh copy of the env file and then afterwards changing APP_PORT to - in your case - 8002

**Comment by Neules** [comment]
Okay. I removed everything, benotes container and directory where I download initial files and started from scratch again, and worked this time.

I tried downloading the files by `wget` method, I don't know if that was the clue (it doesn't make sense) and as you, I have only changed APP_PORT.
Thanks for your time (and patience). Closing the issue :)
