### ISSUE TITLE
Markdown and edit function

### ISSUE THREAD

**Issue by Neules** [fr0tt/benotes#72]
When you use markdown in order to list links you cannot edit later. Using a normal user (created after admin user).

E.g.

I create a new post with this content:

```markdown
- [link](https://www.google.com)
- [link2](https://www.google.com)
```

and then Save it. If then I want to edit and add another link:

```markdown
- [link](https://www.google.com)
- [link2](https://www.google.com)
- [link3](https://www.google.com)
```

and save, next time you edit the post link3 will not appear (will not be saved).

EDIT: also, markdown is not rendering properly? it should be a [link](https://www.google.com), not a literal `[link](https://blahblahblah.com)`

**Comment by fr0tt** [comment]
I tried it and works just as expected on my end.

Converting a markdown link to a link displaying only a title is not supported at the [moment] (https://github.com/ueberdosis/tiptap/issues/2434). 
All links are automatically turned into links regardless.

You can also try out this if you want to see more than just the link: 
```
<https://yourlink.com>
```

**Comment by Neules** [comment]
Right. So I'm closing issue, thanks
