### ISSUE TITLE
Data not being saved

### ISSUE THREAD

**Issue by Bag72** [fr0tt/benotes#73]
I've just started with Benotes and I'm impressed with the I/F.   Simple and easy to use.  I've been using it OK for about a week.  I like it a lot.

However, yesterday I had some data that was not saved.  I noticed a little box in the bottom left which said there was an error.   I almost missed it.   Could it be moved centre screen or up by the Save button to make it more obvious.    As pressing save closes the page, and remember there was an error, I lost my input.  I then started copying the page before saving just in case and it happened a few times.

Then I found a record that had not given an error message but hadn't saved the data.   I edited it again thinking that I hadn't saved it and it closed but didn't save.  No error messages at all.  I could make some changes and it would be saved but others wouldn't be saved.  All failed saves did not give any errors at all.  Obviously I have no idea how long this has been happening it could have been from day 0.

Anyone have an ideas on how I can fix this or diagnose the issue.

I am on a QNAP NAS running the latest QTS Hero.  The App is in a Docker Container and set up on NGinx.   Access works fine and everything appears OK.  Only issues are the occasional error failing to save and it simply not saving with no errors.

**Comment by fr0tt** [comment]
Interesting. Thanks for writing. 
Seems like a good idea to only navigate back if there was no error. (Initially I wanted to redirect before that could be checked in order to offer a better/smoother performance.)

Can you reproduce it ? Does it only happen with certain posts ? Or after a certain amount of time ? 
Any errors you can find in your browser's console or in `/var/www/storage/logs/laravel.log` would be appreciated.

**Comment by fr0tt** [comment]
Perhaps you can recreate a version of your post that fails, containing only the bar minimum and doesn't disclose anything personal that you could share.

Could you post (at least) the 24 previous lines of the log file (, because there are far more important) ?

**Comment by Bag72** [comment]
I've attached a copy of the text that fails.   I've removed the domain name but everything else is the same.

I created the file in Benote with no problems then went back later to format it properly and add in the config details.   It wouldn't save the changes and didn't raise any error messages.

Also attached is the complete log file from the system.
[Add Torrent to System.txt](https://github.com/fr0tt/benotes/files/11320740/Add.Torrent.to.System.txt)
[laravel.log](https://github.com/fr0tt/benotes/files/11320743/laravel.log)

Let me know if you need anything else.

**Comment by fr0tt** [comment]
Thanks. It might have something to do with that domain/link. Can you try to create a post only containing it and see if that fails or not ?

**Comment by Bag72** [comment]
Mmmm. I can create a note with the domain in without an issue.  I also managed to edit that note.

I have played about with it and I've noticed that it is removing formatting spaces.   I can add text and it saves fine but it removes leading spaces and padded spaces on every save.   This explains why there are no errors, the system is actually saving the data.

As I am trying to format the text by entering spaces it appears that it is not saving but it is.

Therefore when I raised this as Data not being saved that is incorrect.   It is modifying data by stripping out extraneous spaces.  Is that deliberate or a bug?

**Comment by fr0tt** [comment]
I'm sorry I didn't answer sooner.
I haven't had the chance to resolve your issue but I wanted to you let you know that I haven't forgotten you yet ;)
Currently I can only say that the ip address does not seem to be the root of the issue (which might have made sense) and your latest log file probably does not include anything intertwined with your issue. (Thou I'm still investigating why that particular error (message) happens.)

**Comment by Bag72** [comment]
OK.  thanks for responding.  I'm going to try embedding the docker container in a LXD container.   See what happens there to fix the writing issue.

The truncation and the reformatting are clearly coding and/or browser issues.  I'll try different browsers to help you diagnose the problem.   When you get around to it ping me and I'll help diagnose where I can.

**Comment by fr0tt** [comment]
So I had some time so can I tell you know:

- Your first (torrent) post actually works just fine for me. It takes one second but it works.
- * * * * * works as expected even if it isn't want your expecting. An asterisk following at some point an other one is interpreted as italic due to the markdown support. It might be possible to exclude this particular pattern but I would usually anyway write it as code.
- Pasting indeed seems to remove empty lines, but it is not something that I could change. This project uses Tiptap and Tiptap doesn't seem to support it. Your docker compose example for instance can be written as a code block and then everything works as you expect it. (I also like to add syntax highlighting in the future which would make this an even better solution.)

**Comment by Bag72** [comment]
I understand about markdown but I interpreted the 'supports both markdown and a rich text editor' as it was optional and it isn't.  So it is 'uses markdown'   How do I use the rich text editor instead of markdown?

I tired code blocks and they still truncated the lines so all the YAML and JSON files are wrong.   How did you do the docker-compose block?

**Comment by fr0tt** [comment]
You use both at the same time. You can either use markdown syntax or use the buttons.

Well I created an empty code block with: 
```

```
and then pasted your content in it.

**Comment by Bag72** [comment]
Ah. OK.  I managed to create one from the markup guide you link too.    So far its allowing me to add them back and now I understand the formatting issue I'm full speed ahead.

Thanks for the help.  It is much appreciated.  I'll close this down and if the errors appear again I'll open another issue.

**Comment by fr0tt** [comment]
If you rather prefer to achieve it without markdown syntax you can also click on the code button and then past your content afterwards inside it.
