### ISSUE TITLE
Small UI glitch when clicking on a post

### ISSUE THREAD

**Issue by Kdecherf** [fr0tt/benotes#77]
Hello,

Edit mode activates when we click on a post. Vertical scrollbar shows up but should not.

![2023-05-04-194557_4480x1440](https://user-images.githubusercontent.com/226063/236287584-5389d9b1-23b2-4e45-a32d-ff636143349b.png)

Edit: seen on Firefox 109

**Comment by fr0tt** [comment]
Hello,

you mean the horizontal scrollbar, right ? :)

I have never had that issue. Strange, I have to play with some browsers. I assume this is on desktop ?

**Comment by Kdecherf** [comment]
Ah yeah, I meant horizontal scrollbar, sorry :sweat_smile:
