### ISSUE TITLE
BasePath support

### ISSUE THREAD

**Issue by tstanciu** [fr0tt/benotes#81]
Hello,
Is there any way to configure Benotes to be accessible to a base path? http://localhost:8000/benotes
It is useful for hosting multiple services behind a reverse proxy. I run Benotes with Docker.
For example:
- https://domain.com/app1
- https://domain.com/benotes
- https://domain.com/app2

Thank you very much!

**Comment by fr0tt** [comment]
Hello,

actually I never tried to do that. It might work, maybe you have to adjust the `APP_URL`

**Comment by EPecherkin** [comment]
@tstanciu such issues are common with routes like https://domain.com/app1 . It is general advise to configure reverse proxy and dns to paths like https://app1.domain.com/
