### ISSUE TITLE
Checking checkbox is broken

### ISSUE THREAD

**Issue by TheZoker** [fr0tt/benotes#82]
When I try to check a checkbox within benotes, I get an index out of range error:
![image](https://github.com/fr0tt/benotes/assets/1368405/634991c2-7dbe-4b9f-ac78-4f381896549d)

**Comment by fr0tt** [comment]
Hey,

thank you for your pull requests!

That is strange. Does it only occur with that post or with a certain browser ? (because it works just fine on my side so far)

**Comment by TheZoker** [comment]
I also testes this in Firefox and there it works.

I tested brave (Version 1.51.114 Chromium: 113.0.5672.92) on two different PCs and both had the same issue

**Comment by fr0tt** [comment]
I've tested it with Firefox, Opera and Edge and it seems to work with all of them. So it might be a problem only appearing in Brave.

**Comment by fr0tt** [comment]
Is it still an issue these days ?

**Comment by TheZoker** [comment]
Thanks for the asking! It seems that the issue has been resolved in one of the updates or within a browser update. I'll close this :)
