### ISSUE TITLE
Removing parent collection not working

### ISSUE THREAD

**Issue by TheSelox** [fr0tt/benotes#83]
Hi, I have a collection `col2` that's a subcollection of `col1`.
When I'm in the edit menu of `col2` and I remove the parent `col1` with the small "x" to move `col2` back to the root level nothing changes after hitting save.
When I'm clicking on "edit" of `col2` again `col1` is still there as the parent.

**Comment by fr0tt** [comment]
Hi,

thank you for pointing this out !
