### ISSUE TITLE
unbound variable

### ISSUE THREAD

**Issue by nocomment-bln** [fr0tt/benotes#86]
I got this issue at first run

-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
-> Executing /entrypoint.d/app_entrypoint.sh
/entrypoint.d/app_entrypoint.sh: line 9: RUN_MIGRATIONS: unbound variable

Any idea ?

Thaanks

**Comment by fr0tt** [comment]
Seems like there is something mixed up.
What installation method did you use and which image and most importantly which .env file ?

Nonetheless it probably can be fixed by adding `RUN_MIGRATIONS=false` in your `.env` file.

**Comment by nocomment-bln** [comment]
hi, thanks for the answer.

I used the docker-compose file and the .env file

RUN_MIGRATIONS=false doesnt changed anything

**Comment by fr0tt** [comment]
Hi,

sorry for the inconvenience !

It should be fixed now with the newest build (so after you pulled the image again).

**Comment by nocomment-bln** [comment]
works now! thanks
