### ISSUE TITLE
Duplicating Collections in Search Input Field

### ISSUE THREAD

**Issue by roughnecks** [fr0tt/benotes#91]
Hello,

anytime I click on the input field of the search form I get duplication of collection (only visually): https://i.imgur.com/R42O021.jpeg

**Comment by fr0tt** [comment]
Hi,

Thanks ! This will be fixed within the next release.

**Comment by roughnecks** [comment]
Hello, I still have the bug.

One thing I'm not sure about the upgrade is that the

    php artisan migrate

command didn't upgrade anything and I have a new "database.sqlite" file inside storage dir.
My DB is instead located at `/var/lib/benotes/notes.sqlite`

Thanks

**Comment by fr0tt** [comment]
Hello,

that's strange. It works on my system. Perhaps your browser still uses a cached older version. Is it still a problem after a hard reload (Ctrl+F5) or when you're using another browser ?

It's intend to upgrade nothing, because this upgrade didn't include any database changes.

The "new" database is for everyone who wants to use it to reduce the setup time when your installing it for the first time.

**Comment by roughnecks** [comment]
I tried hard reloading but it's still the same. It logs me out and I log back in.

I had this issue while upgrading tho, forgot to mention it:

    php artisan cache:clear
    Failed to clear cache. Make sure you have the appropriate permissions.

I checked all of the cache folder inside the project and all of them are writeable by my user.
Is there any particular folder I should check for permissions?

```
find . -type d -name "cache"
./bootstrap/cache
./vendor/doctrine/cache
./vendor/psr/cache
./storage/framework/cache
```

**Comment by roughnecks** [comment]
I changed owner again to all files in my project directory and now was able to clear the cache, although the issue is still there.. even from another browser.

**Comment by fr0tt** [comment]
`storage` and `bootstrap/cache` should be both accessible for your own user and your webserver's user.
But I guess that's not the issue here. Let's look at this from a different angle. Can you notice a difference regarding scrolling on mobile and your backup issue ?

**Comment by roughnecks** [comment]
Yes, I could take a backup and the scrolling issue looks like fixed.

**Comment by fr0tt** [comment]
I think I figured it out. There are at least two ways to accomplish this outcome and I fixed one but not the other

**Comment by roughnecks** [comment]
fixed as well. Thanks
