### ISSUE TITLE
Importing Bookmarks: Failed. Error 500

### ISSUE THREAD

**Issue by roughnecks** [fr0tt/benotes#92]
Hi,

I tried importing bookmarks from Firefox and Chrome exports.. both failed with the error in subject.

If you can tell how to check for more detailed error messages I would appreciate - or if you have a solution, that is :)

I can see some of them were imported, but like 10 out of 100?

**Comment by fr0tt** [comment]
It has nothing to do with the infrastructure you're using. 
Keep in mind to change the variables back to their original values after testing.

**Comment by roughnecks** [comment]
OK, I looked at the log and found out this:

```
[2023-10-16 10:38:02] local.ERROR: Unable to init from given url (https://discordapp.comundefined//discord.com/assets/652f40427e1f5186ad54836074898279.png). {"userId":1,"exception":"[o
bject] (Intervention\\Image\\Exception\\NotReadableException(code: 0): Unable to init from given url (https://discordapp.comundefined//discord.com/assets/652f40427e1f5186ad548360748982
79.png). at /home/notes/benotes/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:85)
[stacktrace]
```

so I deleted my discord bookmark and it almost worked.. "almost" because this time it gave me a 504 IIRC but the laravel.log shows nothing new and my bookmarks seems to be all there (cannot be 100% sure tho)

**Comment by fr0tt** [comment]
I'm curious, did your Discord bookmark originally look like this or was there no "undefined" in it before ?

Seems the task took longer then your PHP configuration allows.

**Comment by roughnecks** [comment]
This is the bookmark: ***@***.***

As for PHP, I will take a look!

**Comment by roughnecks** [comment]
I edited my previous comment with the actual bookmark, sorry but replying from email messed up!
