### ISSUE TITLE
[feature request] lock notes in place (PWA on mobile issue)

### ISSUE THREAD

**Issue by roughnecks** [fr0tt/benotes#94]
Hello again,

on my mobile phone, using the PWA, I have the following issue: when I want to scroll down the list of notes, I always end up reordering them, because I have to touch on a note and keep pressed to scroll.

The only solution I have found so far is to touch on the right side where there is some blank space, so I can scroll freely.

If we could have a way to lock the notes in place, it would be awesome.

**Comment by fr0tt** [comment]
Hi again,

Which browser are your using ?

Because this was an issue in the past but I increased the time needed in order for it to reorder the post instead of scrolling down/up. 
Are you always having trouble with this or only when trying to slowly(!) scroll down/up ?

**Comment by roughnecks** [comment]
Chrome.

It happens very often, not sure if I am slow or perhaps my phone is (running on an old Redmi 6A).

**Comment by fr0tt** [comment]
I tested it with Chrome as well. 

Strange, then I'm going to increase the time needed for reordering.

**Comment by roughnecks** [comment]
Thanks, appreciated.
