### ISSUE TITLE
Pasting HTML code to view

### ISSUE THREAD

**Issue by pheonix-devapps** [fr0tt/benotes#95]
For example:
HTML code link:
https://www.upavidhi.com/sutra/ekadhikena-purvena#:~:text=28%20%2B%20165,for%20something%20like%3A

<table cellpadding="0" cellspacing="5px" width="100%">
	<tbody><tr>
		<td class="textNormal bolden mathsFont" align="left" valign="top" width="20px" nowrap="" rowspan="4">&nbsp;</td>
		<td class="textNormal bolden mathsFont" align="left" valign="top" colspan="2" width="50%">Steps</td>
		<td class="textNormal bolden mathsFont" align="left" valign="top" width="50%">28 + 165</td>
	</tr>
	<tr>
		<td class="textNormal mathsFont" align="left" valign="top">1.</td>
		<td class="textNormal mathsFont" align="left" valign="top">Equate the digits of both the numbers by prefixing imaginary Zeroes in front, and start counting upwards.</td>
		<td class="textNormal mathsFont" align="left" valign="top">In this case,<br>
		&nbsp;&nbsp;<span class="faden">0</span> 2 8<br>
		+&nbsp;1 6 5<br>
		--------<br>
		</td>
	</tr>
	<tr>
		<td class="textNormal mathsFont" align="left" valign="top">2.</td>
		<td class="textNormal mathsFont" align="left" valign="top">While summing the digits, place a dot on the previous digit for whichever digit caused the count greater than 10, and continue counting by removing the Ten's place.</td>
		<td class="textNormal mathsFont" align="left" valign="top">In this case,<br>
		&nbsp;&nbsp;<span class="faden">0</span> 2<sup>o</sup>8<br>
		+&nbsp;1 6 5<br>
		--------<br>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3
		</td>
	</tr>
	<tr>
		<td class="textNormal mathsFont" align="left" valign="top">3.</td>
		<td class="textNormal mathsFont" align="left" valign="top">While counting consider the dots in the column as an ekādhika, or +1.</td>
		<td class="textNormal mathsFont" align="left" valign="top">In this case,<br>
		&nbsp;&nbsp;<span class="faden">0</span> 2<sup>o</sup>8<br>
		+&nbsp;1 6 5<br>
		--------<br>
		&nbsp;&nbsp;1 9 3, which is the answer!
		</td>
	</tr>
</tbody></table>

**Comment by fr0tt** [comment]
This is currently not possible because HTML code most likely contains elements that aren't supported elements of the editor
